<?php declare(strict_types = 1);

return [
    
    [['GET','POST'], '/outlets', ['Modules\Outlets\Controllers\Outlets', 'outletList'],['outlets','customer_list']],
    [['GET','POST'], '/outletassignment', ['Modules\Outlets\Controllers\Outlets', 'OutletAssignment'], ['OutletAssignment', 'loggedin']],
    [['GET','POST'], '/competitorAnalysis', ['Modules\Outlets\Controllers\Outlets', 'competitorAnalysis'], ['competitor_analysis', 'loggedin']],
    [['GET','POST'], '/classification', ['Modules\Outlets\Controllers\Outlets', 'classification'], ['classification', 'classfication']],
    [['GET','POST'], '/addeditoutlets/{pk}', ['Modules\Outlets\Controllers\Outlets', 'addeditOutlet'],['outlets_addedit','loggedin']],  
    [['GET','POST'], '/outlet/{pk}', ['Modules\Outlets\Controllers\Outlets', 'outletsingle'],['outletsingle','loggedin']],  
    [['GET','POST'], '/outletorg/{id}', ['Modules\Outlets\Controllers\Outlets', 'outletOrg'],['outletorg','loggedin']],
    [['GET','POST'], '/internalNotes/{id}', ['Modules\Outlets\Controllers\Outlets', 'internalNotes'],['internalNotes','loggedin']],
    [['GET','POST'], '/outlet/account/{id}', ['Modules\Outlets\Controllers\Outlets', 'outletAccount'], ['outletAccount', 'loggedin']],
    [['GET','POST'], '/outlet/mapping/{id}', ['Modules\Outlets\Controllers\Outlets', 'OutletMapping'], ['OutletMapping', 'loggedin']],
    [['GET','POST'], '/outlet/stock/{id}', ['Modules\Outlets\Controllers\Outlets', 'outletStock'], ['outletStock', 'loggedin']],
    [['GET','POST'], '/outlet/target/{id}', ['Modules\Outlets\Controllers\Outlets', 'outletTarget'], ['outletTarget', 'loggedin']],

    [['GET','POST'], '/outlet/byOutletCode/{outletCode}', ['Modules\Outlets\Controllers\Outlets', 'getOutletByOutletCode'],['outletByoutletCode', 'loggedin']],  

    [['GET','POST'], '/outlets/tags', ['Modules\Outlets\Controllers\Outlets', 'tags'], ['outlet_tags', 'customer_tags']],
    [['GET','POST'], '/leads', ['Modules\Outlets\Controllers\Outlets', 'leads'], ['leads','customer_tags']],

    // contact list
    [['GET','POST'], '/contact', ['Modules\Outlets\Controllers\Outlets', 'contact'], ['contact','customer_tags']],
    [['GET','POST'], '/contact/getTerrId/{id}', ['Modules\Outlets\Controllers\Outlets', 'getTerrId'], ['getTerrId','loggedin']],
    // end contact list 

    [['GET','POST'], '/outlet/AddEditoutletOrgData/{id}', ['Modules\Outlets\Controllers\Outlets', 'AddEditoutletOrgData'], ['AddEditoutletOrgData', 'loggedin']],
    [['GET','POST'], '/outlet/AddEditoutletAddress/{id}', ['Modules\Outlets\Controllers\Outlets', 'AddEditoutletAddress'], ['AddEditoutletAddress', 'loggedin']],
    
//    [['GET','POST'], '/outletOutComes', ['Modules\Outlets\Controllers\Outlets', 'outletOutComes'],['outlet_outcomes','loggedin']],      
    [['GET','POST'], '/outletsearch', ['Modules\Outlets\Controllers\Outlets', 'outletAutoComplete'],['outletAutoComplete','loggedin']],      
    [['GET','POST'], '/outletOrgSearch', ['Modules\Outlets\Controllers\Outlets', 'outletOrgDataAutoComplete'],['outletOrgDataAutoComplete','loggedin']],      
    
    
    /*API Document Keys*/
    [['GET','POST','PUT','DELETE'], '/api/getOutletTypes', ['Modules\Outlets\Controllers\API', 'getOutletTypes'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getParentOutlets', ['Modules\Outlets\Controllers\API', 'getParentOutlets'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getDefaultParentOutlets', ['Modules\Outlets\Controllers\API', 'getDefaultParentOutlets'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getAllOutlet', ['Modules\Outlets\Controllers\API', 'getAllOutlet'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/createOutlet', ['Modules\Outlets\Controllers\API', 'createOutlet'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletMappedWithParent', ['Modules\Outlets\Controllers\API', 'outletMappedWithParent'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getEmployeeBeats', ['Modules\Outlets\Controllers\API', 'getEmployeeBeats'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletMappedWithBeats', ['Modules\Outlets\Controllers\API', 'outletMappedWithBeats'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletVerifySendOTP', ['Modules\Outlets\Controllers\API', 'outletVerifySendOTP'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletVerify', ['Modules\Outlets\Controllers\API', 'outletVerify'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletById', ['Modules\Outlets\Controllers\API', 'getOutletById'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getEmpOutlets', ['Modules\Outlets\Controllers\API', 'getEmpOutlets'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/checkinOld', ['Modules\Outlets\Controllers\API', 'checkinOld'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/checkoutOld', ['Modules\Outlets\Controllers\API', 'checkoutOld'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletMediaType', ['Modules\Outlets\Controllers\API', 'getOutletMediaType'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletCheckinMedia', ['Modules\Outlets\Controllers\API', 'outletCheckinMedia'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/checkin', ['Modules\Outlets\Controllers\API', 'checkin'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/checkout', ['Modules\Outlets\Controllers\API', 'checkout'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/checkInOutStatus', ['Modules\Outlets\Controllers\API', 'checkInOutStatus'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/search', ['Modules\Outlets\Controllers\API', 'search'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletHistory', ['Modules\Outlets\Controllers\API', 'outletHistory'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/outletFilter', ['Modules\Outlets\Controllers\API', 'outletFilter'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getAllOutletOrders', ['Modules\Outlets\Controllers\API', 'getAllOutletOrders'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletOrderFilter', ['Modules\Outlets\Controllers\API', 'getOutletOrderFilter'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletRecentOrders', ['Modules\Outlets\Controllers\API', 'getOutletRecentOrders'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOrderById', ['Modules\Outlets\Controllers\API', 'getOrderById'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOrderByIdNew', ['Modules\Outlets\Controllers\API', 'getOrderByIdNew'],['getOrderByIdNew','loggedin']],
    
    [['GET','POST','PUT','DELETE'], '/api/getDailyMtdSales', ['Modules\Outlets\Controllers\API', 'getDailyMtdSales'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getLastThreeMonthOrder', ['Modules\Outlets\Controllers\API', 'getLastThreeMonthOrder'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getCompetitors', ['Modules\Outlets\Controllers\API', 'getCompetitors'],['Outlets','any']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletOutcomes', ['Modules\Outlets\Controllers\API', 'getOutletOutcomes'],['Outlets','any']],
    [['GET','POST','PUT','DELETE'], '/api/getClassifications', ['Modules\Outlets\Controllers\API', 'getClassifications'],['classifications','any']],
    [['GET','POST','PUT','DELETE'], '/api/getLastLocation', ['Modules\Outlets\Controllers\API', 'getLastLocation'],['Outlets','any']],

    [['GET','POST','PUT','DELETE'], '/api/getActivityKpis', ['Modules\Outlets\Controllers\API', 'getActivityKpis'],['getActivityKpis','any']],

    [['GET','POST','PUT','DELETE'], '/api/getTopBrands', ['Modules\Outlets\Controllers\API', 'getTopBrands'],['getTopBrands','any']],

    [['GET','POST','PUT','DELETE'], '/api/getManagerActivityKpis', ['Modules\Outlets\Controllers\API', 'getManagerActivityKpis'],['getManagerActivityKpis','any']],
    
    [['GET','POST','PUT','DELETE'], '/api/validateOutlet', ['Modules\Outlets\Controllers\API', 'validateOutlet'],['Outlets','loggedin']],

    [['GET','POST','PUT','DELETE'], '/api/getAllBrand', ['Modules\Outlets\Controllers\API', 'getAllBrand'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getVisitFrequency', ['Modules\Outlets\Controllers\API', 'getVisitFrequency'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletSubType', ['Modules\Outlets\Controllers\API', 'getOutletSubType'],['Outlets','loggedin']],

    //OnBoard API's
    [['GET','POST','PUT','DELETE'], '/api/onBoardOutlets', ['Modules\Outlets\Controllers\API', 'onBoardOutlets'],['Outlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/searchExistsOutlet', ['Modules\Outlets\Controllers\API', 'searchExistsOutlet'],['searchExistsOutlet','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/searchOutlets', ['Modules\Outlets\Controllers\API', 'searchOutlets'],['searchOutlets','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletDetails', ['Modules\Outlets\Controllers\API', 'getOutletDetails'],['getOutletDetails','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/addOutletRequest', ['Modules\Outlets\Controllers\API', 'addOutletRequest'],['addOutletRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/searchAddress', ['Modules\Outlets\Controllers\API', 'searchAddress'],['searchAddress','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getAddressBeats', ['Modules\Outlets\Controllers\API', 'getAddressBeats'],['getAddressBeats','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/addOutletOrgDataRequest', ['Modules\Outlets\Controllers\API', 'addOutletOrgDataRequest'],['addOutletOrgDataRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/onBoardStatus', ['Modules\Outlets\Controllers\API', 'onBoardStatus'],['onBoardStatus','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletOrgData', ['Modules\Outlets\Controllers\API', 'getOutletOrgData'],['getOutletOrgData','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardRequest', ['Modules\Outlets\Controllers\API', 'getOnBoardRequest'],['getOnBoardRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletMapping', ['Modules\Outlets\Controllers\API', 'getOutletMapping'],['getOutletMapping','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/addOutletMappingRequest', ['Modules\Outlets\Controllers\API', 'addOutletMappingRequest'],['addOutletMappingRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/changeRequestStatus', ['Modules\Outlets\Controllers\API', 'changeRequestStatus'],['changeRequestStatus','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getRequestLog', ['Modules\Outlets\Controllers\API', 'getRequestLog'],['getRequestLog','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/submitRequest', ['Modules\Outlets\Controllers\API', 'submitRequest'],['submitRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getPendindApprovalRequest', ['Modules\Outlets\Controllers\API', 'getPendindApprovalRequest'],['getPendindApprovalRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/approveRequest', ['Modules\Outlets\Controllers\API', 'approveRequest'],['approveRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/rejectRequest', ['Modules\Outlets\Controllers\API', 'rejectRequest'],['rejectRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getFilterRequest', ['Modules\Outlets\Controllers\API', 'getFilterRequest'],['getFilterRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardRequestAddressById', ['Modules\Outlets\Controllers\API', 'getOnBoardRequestAddressById'],['getOnBoardRequestAddressById','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/deleteOnBoardRequestAddress', ['Modules\Outlets\Controllers\API', 'deleteOnBoardRequestAddress'],['deleteOnBoardRequestAddress','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getRequiredFields', ['Modules\Outlets\Controllers\API', 'getRequiredFields'],['getRequiredFields','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardWindow', ['Modules\Outlets\Controllers\API', 'getOnBoardWindow'],['getOnBoardWindow','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletsByTerritory', ['Modules\Outlets\Controllers\API', 'getOutletsByTerritory'],['getOutletsByTerritory','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/updateOutletRequest', ['Modules\Outlets\Controllers\API', 'updateOutletRequest'],['updateOutletRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/updateOutletOrgDataRequest', ['Modules\Outlets\Controllers\API', 'updateOutletOrgDataRequest'],['updateOutletOrgDataRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletTags', ['Modules\Outlets\Controllers\API', 'getOutletTags'],['getOutletTags','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/deleteOnBoardRequest', ['Modules\Outlets\Controllers\API', 'deleteOnBoardRequest'],['deleteOnBoardRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardAddressStatus', ['Modules\Outlets\Controllers\API', 'getOnBoardAddressStatus'],['getOnBoardAddressStatus','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletIdByRequest', ['Modules\Outlets\Controllers\API', 'getOutletIdByRequest'],['getOutletIdByRequest','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/deleteMedia', ['Modules\Outlets\Controllers\API', 'deleteMedia'],['deleteMedia','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getAddressMedia', ['Modules\Outlets\Controllers\API', 'getAddressMedia'],['getAddressMedia','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/deleteAddressMedia', ['Modules\Outlets\Controllers\API', 'deleteAddressMedia'],['deleteAddressMedia','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardWindowByTerritory', ['Modules\Outlets\Controllers\API', 'getOnBoardWindowByTerritory'],['getOnBoardWindowByTerritory','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/deleteRequestMapping', ['Modules\Outlets\Controllers\API', 'deleteRequestMapping'],['deleteRequestMapping','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/updateOutletOrgDataMedia', ['Modules\Outlets\Controllers\API', 'updateOutletOrgDataMedia'],['updateOutletOrgDataMedia','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/createRequestToOutlet', ['Modules\Outlets\Controllers\API', 'createRequestToOutlet'],['createRequestToOutlet','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOutletRcpaSgpi', ['Modules\Outlets\Controllers\API', 'getOutletRcpaSgpi'],['getOutletRcpaSgpi','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardNotifications', ['Modules\Outlets\Controllers\API', 'getOnBoardNotifications'],['getOnBoardNotifications','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getOnBoardRequestByStatus', ['Modules\Outlets\Controllers\API', 'getOnBoardRequestByStatus'],['getOnBoardRequestByStatus','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getPositionTreeView', ['Modules\Outlets\Controllers\API', 'getPositionTreeView'],['getPositionTreeView','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getprescriberTallyWidget', ['Modules\Outlets\Controllers\API', 'getprescriberTallyWidget'],['getprescriberTallyWidget','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getpresciberStatus', ['Modules\Outlets\Controllers\API', 'getpresciberStatus'],['getpresciberStatus','loggedin']],
    [['GET','POST','PUT','DELETE'], '/api/getLanguages', ['Modules\Outlets\Controllers\API', 'getLanguages'],['getLanguages','loggedin']],  
    
];